# Generated by Django 5.2.4 on 2025-07-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExardProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('alpha_number', models.CharField(max_length=100)),
                ('bap_number', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
